name: bca_student_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  http: ^1.3.0
  flutter_profile_picture: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.2.1
  lottie: ^2.3.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg
    - assets/loading.json
